HR_System/HR_System/Controllers/DepartmentController.cs
using HR_System.data;
using HR_System.service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HR_System.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService departmentService;

        public DepartmentController(IDepartmentService _departmentService)
        {
            departmentService = _departmentService;
        }
        public IActionResult NewDepartment()
        {
            ViewData["ISValid"] = false;
            return View();
        }
        public IActionResult DepartmentList()
        {
            List<Department> li = departmentService.LoadAll();
            return View(li);
        }

        public IActionResult SaveData(Department dept)
        {
            departmentService.Insert(dept);
            ViewData["ISValid"] = false;
            return View("NewDepartment");
        }

        public IActionResult SearchData()
        {
            string name = Request.Form["txtSearch"];
            List<Department> li = departmentService.Search(name);
            return View("DepartmentList",li);
        }

        public IActionResult DeleteData(int id)
        {
            departmentService.Remove(id);
            List<Department> li = departmentService.LoadAll();
            return View("DepartmentList",li);
        }

        public IActionResult Edit(int id)
        {
            Department dept= departmentService.load(id);
            ViewData["ISValid"] = true;
            return View("NewDepartment", dept);
        }

        public IActionResult UpdateData(Department dept)
        {
            departmentService.Update(dept);
            ViewData["ISValid"] = true;
            return View("NewDepartment");
        }
    }
}

HR_System/HR_System/Controllers/EmployeeController.cs
using HR_System.data;
using HR_System.Models;
using HR_System.service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace HR_System.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private  IEmployeeService employeeService;
        private  IConfiguration configuration;
        private  IDepartmentService departmentService;

        public EmployeeController(IEmployeeService _employeeService,IConfiguration _configuration,IDepartmentService _departmentService)
        {
            employeeService = _employeeService;
            configuration = _configuration;
            departmentService = _departmentService;
        }
        public IActionResult Index(VMEmployee vm)
        {
            ViewData["ISValid"] = false;
            vm.lidepartments = departmentService.LoadAll();
            return View("NewEmployee",vm);
        }

        public IActionResult SaveData(VMEmployee vm)
        {
            string filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\" + configuration["filePath"], vm.employee.ProfileImage.FileName);
            vm.employee.ProfileImage.CopyTo(new FileStream(filePath, FileMode.Create));
            vm.employee.path = "http://localhost/HR_System/" + configuration["filePath"] + configuration["filePath"] + "/" + vm.employee.ProfileImage.FileName;
            employeeService.Insert(vm.employee);
            vm.lidepartments = departmentService.LoadAll();
            ViewData["ISValid"] = false;
            return View("NewEmployee",vm);
        }

        public IActionResult EmployeeList()
        {
            List<Employee> li = employeeService.LoadAll();
            return View(li);
        }

        public IActionResult SearchData()
        {
            string name = Request.Form["txtSearch"];
            List<Employee> li = employeeService.Search(name);
            return View("EmployeeList", li);
        }

        public IActionResult EditData(int id,VMEmployee vm)
        {
            vm.employee = employeeService.Edit(id);
            ViewData["ISValid"] = true;
            vm.lidepartments = departmentService.LoadAll();
            return View("NewEmployee",vm);
        }

        public IActionResult UpdateData(VMEmployee vm)
        {
            employeeService.Update(vm.employee);
            ViewData["ISValid"] = true;
            vm.lidepartments = departmentService.LoadAll();
            return View("NewEmployee", vm);
        }

        public IActionResult DeleteData(int id)
        {
            employeeService.Remove(id);
            List<Employee> li = employeeService.LoadAll();
            return View("EmployeeList", li);
        }
    }
}

HR_System/HR_System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HR_System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HR_System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HR_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

HR_System/HR_System/Views/Shared/_LayoutView.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_LayoutView</title>
    <script src="~/twitter-bootstrap/js/bootstrap.js"></script>
    <link href="~/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <div class="container-fluid>
        <div class="row">
            <nav class="navbar-default" style="background: #337ab7;">
                <div class="navbar-brand" style=" color: white;">
                    HR system
                </div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-target="#menu1" data-toggle="collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="menu1" class="navbar-collapse collapse">
                    @if (signInManager.IsSignedIn(User))
                    {
                        <ul class="nav navbar-nav">
                            <li>
                                <a asp-action="NewDepartment" asp-controller="Department" style="color: white;">New Department</a>
                            </li>
                            <li>
                                <a asp-action="Departmentlist" asp-controller="Department" style="color: white;">Department List</a>
                            </li>
                            <li>
                                <a asp-action="Index" asp-controller="Employee" style=" color: white;">New Employee</a>
                            </li>
                            <li>
                                <a asp-action="EmployeeList" asp-controller="Employee" style=" color: white;">Employee List</a>
                            </li>
                        </ul>
                    }
                <ul class="nav navbar-nav navbar-right">
                    @if (signInManager.IsSignedIn(User))
                    {
                        <li><a asp-action="SignOut" asp-controller="Account" style="color: white;"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>

                    }
                    else
                    {
                        <li><a asp-action="Index" asp-controller="Account" style="color: white;"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        <li><a asp-action="SignIn" asp-controller="Account" style="color: white;"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>

                    }

                </ul>
                    </div>

            </nav>
        </div>

        <div class="row">
            <div class="col-xs-12">
                @RenderSection("Body", false)

            </div>

        </div>
    </div>
</body>
</html>